### ISSUE TITLE
updateClasses() in jsonparser.js : unnötiges Sortieren der classNames?

### ISSUE THREAD

**Issue by nicolasraube** [gruener-campus-malchow/vertretungsplan#100]
@niccokunzmann In dieser Funktion werden die classNames mit einer RegExp sortiert:

```var numberPattern = new RegExp("^\\d+");
      classNames.sort(function (s1, s2) {
          var ret = parseInt(numberPattern.exec(s1)) - parseInt(numberPattern.exec(s2));
          if (ret != 0) {
              return ret;
          } else if (s1 < s2) {
              return -1;
          } else if (s1 > s2) {
              return 1;
          }
          return 0;
        });

Ist das wirklich notwendig? Die API liefert ja schon alles sortiert und wenn ich diesen Code lösche, sehe ich keinen Unterschied.

**Comment by niccokunzmann** [comment]
Ich weiß nicht, in welcher Reihenfolge es ankommt. Es sortiert zuerst nach Zahlen und dann nach klasse a, klasse b, ... kann weg, wenn ihr es nciht braucht. Das habe ich da in der Nacht geschrieben. bei sowas kann ich immer schlecht reflektieren, ob es Nutzen hat.

**Comment by niccokunzmann** [comment]
Ich weiß nicht, in welcher Reihenfolge es ankommt. Es sortiert zuerst nach Zahlen und dann nach klasse a, klasse b, ... kann weg, wenn ihr es nciht braucht. Das habe ich da in der Nacht geschrieben. bei sowas kann ich immer schlecht reflektieren, ob es Nutzen hat.

**Comment by nicolasraube** [comment]
Gut, dann würde ich das erstmal auskommentieren.

**Comment by niccokunzmann** [comment]
Vorschlag, damit die Issue geschlossen werden kann:

- [x] Quellcode löschen (Er ist in der Historie und der Issue. wenn wir ihn brauchen, holen wir ihn uns)
- [x] In der API dokumentieren, dass eine bestimmte Reihenfolge erwartet wird.

**Comment by nicolasraube** [comment]
Gut, beim Sortieren der Dropdown-Optionen wird das aber auf jeden Fall noch weiterhelfen.
