### ISSUE TITLE
Interval, der auf neuen Plan prüft

### ISSUE THREAD

**Issue by nicolasraube** [gruener-campus-malchow/vertretungsplan#109]
Wenn ein neuer oder aktualisierter Plan vorhanden ist, muss sich der Plan automatisch aktualisieren.

**1)** Man könnte das so umsetzen, dass es einen Interval gibt, der in bestimmten Abständen immer das letzte Änderungsdatum abfragt und wenn es ein neues ist, den Plan herunterlädt. Das müsste so noch in der API geändert werden.

**2)** Ansonsten könnte man das lösen, indem der Interval eine XmlHttpRequest ausführt und das Json herunterlädt. Dann sollte geprüft werden, ob sich etwas verändert hat und der Plan kann heruntergeladen werden.

Wenn der neue Plan heruntergeladen wurde, müssen alle Kästen und die Infos im Header gelöscht werden und die Funktion updatePlan() aufgerufen werden.

@ijontychie Welche Variante ist passender? Gibt es eine bessere Lösung?

**Comment by niccokunzmann** [comment]
Ich hätte noch den Vorschlag, dass der Plan die Seite neu lädt, z.B. nach 1 Minute. (Sowas wir F5 drücken).

**Comment by nicolasraube** [comment]
Ok, das ist wahrscheinlich am Besten... 😆

**Comment by niccokunzmann** [comment]
Kann das geschlossen werden?

**Comment by nicolasraube** [comment]
Ja, der Plan aktualisiert sich jetzt.
