### ISSUE TITLE
Pw falsch bei Android Stock Browser

### ISSUE THREAD

**Issue by nicolasraube** [gruener-campus-malchow/vertretungsplan#111]
Viele Schüler haben das Problem, dass sie, wenn sie das Passwort eingegeben haben, die Fehlermeldung "Das eingegebene Passwort ist falsch." bekommen. Benutzte Browser waren:
- mehrmals vorinstallierter Samsung Browser
- 1x Chrome auf Samsung Gerät

Wenn ich meinen vorinstallierten Browser nutze, geht es auch nicht.
Die Fehlerquelle ist unbekannt.

**Comment by Ritze279** [comment]
Bei Chrome könnte vielleicht eine veraltete Version der Grund sein.

**Comment by nicolasraube** [comment]
Laut dem Schüler hat er die neueste Version installiert.

**Comment by Ritze279** [comment]
Bei mir (PC) funktioniert es unter folgenden Browsern:

- Google Chrome
- Microsoft Edge
- Mozilla Firefox

- Safari (IPhone)

Der Internet Explorer gibt mir den Fehler zurück.

**Comment by nicolasraube** [comment]
array.includes()
string.startsWith()
Führte bei mir im IE immer zu einem Fehler. Ich starte gleich eine Pull Request, die diese Issue fixen sollte.

**Comment by nicolasraube** [comment]
Fixed! 😓
