### ISSUE TITLE
Parameter Dokumentieren

### ISSUE THREAD

**Issue by niccokunzmann** [gruener-campus-malchow/vertretungsplan#117]
Die Parameter, die man der plan.html übergeben werden können haben alle einen Zweck.
Können wir die dokumentieren?

Ich schlage folgende Form vor:

---

Scrollen einschalten
---------------------

Parameter: `foyer=true`

Bescheribung: Das schaltet das automatisch Scrollen ein, sodass alle Informationen mal auf dem Vertretungsplan sichtbar sind.

---

**Comment by niccokunzmann** [comment]
Welche parameter gibt es, sind alle dokumentiert?

**Comment by nicolasraube** [comment]
Das sind alle, die es bisher gibt.
