### ISSUE TITLE
Grid in CSS

### ISSUE THREAD

**Issue by niccokunzmann** [gruener-campus-malchow/vertretungsplan#138]
ich habe even vom Mozilla einen Newsletter bekommen.
https://www.mozilla.org/en-US/developer/css-grid/?utm_source=dev-newsletter&utm_medium=email&utm_campaign=mar23-2017
Darin wird CSS-Grid vorgestellt. Vielleicht wollt ihr das mal ausprobieren.

**Comment by nicolasraube** [comment]
Danke für den Tipp 😄 .
