### ISSUE TITLE
Filter for Klassenstufe

### ISSUE THREAD

**Issue by ijontychie** [gruener-campus-malchow/vertretungsplan#152]
needed a filter for listing all 7th grades, 8,th grades, etc... something like
http://vertretung.quelltext.eu/plan.html?cert=*****&klassenstufe=7
instead of
http://vertretung.quelltext.eu/plan.html?cert=*****&klasse=7f

**Comment by nicolasraube** [comment]
This parameter exists and is described here: https://github.com/gruener-campus-malchow/vertretungsplan/blob/master/docs/url-parameter.md#bestimmte-klassenstufen-anzeigen .
