### ISSUE TITLE
Schul-Cloud Anbinden?

### ISSUE THREAD

**Issue by niccokunzmann** [gruener-campus-malchow/vertretungsplan#153]
Hallo,

ich mache gerade meine Masterarbeit bei der Schul-Cloud. Mein Ziel: Schülern ermöglichen, ihre Schul-IT mit zu programmieren.
Ihr macht da ja gerade, deswegen wollte ich fragen, ob das interessant ist bzw. ob ihr beim [Hackathon](https://eventyay.com/e/323333fe/) mit bei sein wollt. 
Die Schul-Cloud ist übrigens hauptsächlich JavaScript/HTML/CSS. Vielleicht lernt ihr das serverseitige JavaScript mit Node.js. 
Ich habe den Programmierern von eurem Vertretungsplan erzählt und sie werden vielleicht helfen, den an die Schul-Cloud mit anzubinden.

Was denkt ihr dazu?

**Comment by nicolasraube** [comment]
Hallo.
Was genau bringt uns das, den Plan an die Schul-Cloud anzubinden?
Soweit ich das verstanden habe, ist die Schul-Cloud ein Dienst, bei dem man Lernstoff hochladen und ansehen kann, richtig?

**Comment by niccokunzmann** [comment]
Das bekommt auch einen Stundenplan und sowas. Insofern sind sachlicher
Natur Vorraussetzungen gegeben.
Für diesen Vertretungsplan hat es keinen Nutzen.
Vielleicht trefft ihr da Leute oder lernt was.
Vielleicht kann es dort eingebunden werden und dann nutzen den Plan auch
andere Schulen.

Wenn ihr wietere Fragen habt, könnt ihr gerne fragen.
Ich wollte euch einladen und von mir aus kann die Issue geschlossen werden.

**Comment by niccokunzmann** [comment]
Cool, dass ihr da wart. Hier gibts Freitickets zum [OpenTechSummit](http://opentechsummit.net), damit eure Eltern und alle anderen auch kostenlos reinkommen: https://eventyay.com/e/5642d9a1/?code=wirliebencoderdojo
