### ISSUE TITLE
Schriftgröße zu klein?

### ISSUE THREAD

**Issue by nicolasraube** [gruener-campus-malchow/vertretungsplan#154]
An der Litfaßsäule sah die Schrift ziemlich klein aus. Sollte die Schrift größer sein?
Wir könnten auch einen neuen URL-Parameter für die Anpassung der Größe einführen. Z.B. ?size=3

**Comment by ijontychie** [comment]
sehr gute idee!

Am 12. Mai 2017 16:41:42 MESZ schrieb Nicolas Raube <notifications@github.com>:
>An der Litfaßsäule sah die Schrift ziemlich klein aus. Sollte die
>Schrift größer sein?
>Wir könnten auch einen neuen URL-Parameter für die Anpassung der Größe
>einführen. Z.B. ?size=3

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
