### ISSUE TITLE
Website geht nicht

### ISSUE THREAD

**Issue by niccokunzmann** [gruener-campus-malchow/vertretungsplan#166]
http://vertretung.quelltext.eu/ ist gerade nicht erreichbar.

**Comment by niccokunzmann** [comment]
Ist das auch für euch so? Es kann sein, dass ich das nur bei mit falsch eingestellt habe.

**Comment by nicolasraube** [comment]
Für mich ist sie erreichbar.

**Comment by niccokunzmann** [comment]
Super!
