### ISSUE TITLE
index.html: Inhalt

### ISSUE THREAD

**Issue by niccokunzmann** [gruener-campus-malchow/vertretungsplan#37]
- [x] Die Überschrift solte sagen, wozu die Seite ist.
- [x] Button: "Vertretungsplan ansehen"
- [x] Das Textfeld sollte beschrieben werden: Wozu wird es gebraucht? Ruhig auch Hintergründe zu der Entscheidung entweder auf der Seite order woanders.

**Comment by nicolasraube** [comment]
Was meinst du mit "Hintergründe zu der Entscheidung"?

**Comment by niccokunzmann** [comment]
Z.B. Warum ein Passwort. Es gibt ja Gründe z.B. die Lehrer zu schützen - Datenschutz. Und die sorgen für die Entscheidung zum Passwort. Wenn wir aber alle Gründe aufschreiben, warum was geschützt werden muss, dann könnten wir eventuell auch andere Lösungen finden, als die eines Passwortes. Vielleicht hat dann weranders eine andere Idee.

**Comment by niccokunzmann** [comment]
Aber das kann auch in eine Dokumentationsdatei.

**Comment by nicolasraube** [comment]
Gut, dann kümmere ich mich später drum.
