### ISSUE TITLE
Use classes to manipualte CSS from JavaScript

### ISSUE THREAD

**Issue by niccokunzmann** [gruener-campus-malchow/vertretungsplan#50]
I believe, JavaScript should not manipulate the style information directly.
Style should be defined in the css files an nowhere else. Therefore:

- add a CSS class
- manipulate the class of the info element if there is no text.

Context:

- https://github.com/gruener-campus-malchow/vertretungsplan/pull/47#pullrequestreview-17655398

**Comment by vanditasharma** [comment]
Is this issue closed somewhere? As I can't find context #47.

**Comment by niccokunzmann** [comment]
@vanditasharma Thanks for pointing this out. I think, the context is gone. I can not find this manipulation either. If you like, you can go through the code and have a look at where it can be improved. 

I saw that there is manipulation of style in JavaScript. https://github.com/gruener-campus-malchow/vertretungsplan/blob/master/js/jsonparser.js#L125 but in this case it can not be removed as the style changes with a variable and there are endless styles which can not be written to a file.

I will close this now as it seems to be resolved. Thanks for notifying.
I think, other issues might be outdated and can be closed, too.
If you like to help out in this project, you are welcome. You to get in contact again if you find something you like to improve. If I can help you  with anything, do not hesitate and ask.
