### ISSUE TITLE
kein neuer Plan => falsches Passwort und weiterleitung

### ISSUE THREAD

**Issue by nicolasraube** [gruener-campus-malchow/vertretungsplan#58]
Wenn die pupilplanapi keinen Vertretungsplan zurückgibt, weil kein neuer Plan vorhanden ist, so wie heute, dann wird angezeigt, dass man ein falsches Passwort eingegeben hat und man wird weitergeleitet. Ich denke dann müsste die API anstatt nichts ein keyword zurückgeben, auf das wir jedes mal prüfen.

**Comment by nicolasraube** [comment]
Hat zufällig jemand noch eine Kopie einer json Datei von der API?

**Comment by niccokunzmann** [comment]
Nein. Sowas sollte in den docs-Ordner: Beispiele, ruhig 3 verschiedene Tage. #61

**Comment by niccokunzmann** [comment]
Vorschlag: die API sollte immer JSON zurück geben. Fehler JSON sähe so aus:

    { "error":ERRORNUMMER, "description": "MENSCHENLESBARE-BESCHREIBUNG" }

z.b.
1. Falsches Passwort
2. Keine Daten
3. Interner Fehler
4. Kein Passwort gegeben: Bitte den certparameter setzen.

Die Idee ist, dass die API immer JSON zurück gibt, damit man sich auf was verlassen kann.

**Comment by nicolasraube** [comment]
@ijontychie Für diese Issue bräuchten wir z.B. Zugriff auf die API. Können wir den bekommen?

**Comment by ijontychie** [comment]
Ich habe an der API nichts geändert, glaube ich. Es sind derzeit vermutlich keine Pläne online... Was sagt denn eine Anfrage? Welche URL benutzt ihr?

**Comment by nicolasraube** [comment]
Ja es sind keine Pläne online, weshalb die API nichts zurückgibt. Es wäre gut, wenn die API in diesem Fall aber ein JSON liefert, wo drin steht, dass es nichts gibt. Wir nutzen die URL http://fbi.gruener-campus-malchow.de/cis/pupilplanapi.php

**Comment by ijontychie** [comment]
Ich habe die API erweitert: Bis übermorgen sind noch zwei test-pläne online Wenn Ihr per GET das Attribut 'dev' mit dem Wert 'wanto' übertragt, bekommt ihr immer diesen Testdatensatz...

**Comment by ijontychie** [comment]
Wenn es keine Pläne gibt, ist das Nullte Element mit dem Wert "false" belegt. Das ist aber noch nicht getestet.

**Comment by ijontychie** [comment]
Achso, LehrerIn ist mit *** belegt, müsste also durch euch gefiltert oder durchgereicht werden. Macht ihr eigentlich eine Version für LehrerInnen?

**Comment by ijontychie** [comment]
Erweitere die API noch schnell um eine Authentifizierung

**Comment by niccokunzmann** [comment]
@ijontychie Du kannst eine neue Issue anlegen, um den Lehrerplan zu beschreiben.

**Comment by nicolasraube** [comment]
Danke
