### ISSUE TITLE
Login ist nicht ganz zu lesen

### ISSUE THREAD

**Issue by niccokunzmann** [gruener-campus-malchow/vertretungsplan#63]
![image](https://cloud.githubusercontent.com/assets/564768/22204348/ce7aed06-e171-11e6-9236-7ce7cd66dc50.png)
Der Loginbutton auf der index.html ist nicht vollständig lesbar.

**Comment by Ritze279** [comment]
@niccokunzmann ich schau mir das nachher mal an.
