### ISSUE TITLE
Passwörter, um default pläne auszuwählen

### ISSUE THREAD

**Issue by niccokunzmann** [gruener-campus-malchow/vertretungsplan#67]
Wie wäre es, wenn man z.B. "test1" als Passwort eingibt und mit den Nummern dann die verschiedenen Testpläne ansehen kann? Für alle geht es dann immernoch mit dem normalen Passwort und wir können gut testen.

Was denkt ihr?

**Comment by nicolasraube** [comment]
Ich denke das ist ein guter Vorschlag.

**Comment by ijontychie** [comment]
Ist im issue #72 beschrieben
