### ISSUE TITLE
Alles JavaScript in head tun

### ISSUE THREAD

**Issue by niccokunzmann** [gruener-campus-malchow/vertretungsplan#68]
Alle JavaScript inlcudes sollten im head sein.
Es gibt sowas wie `window.onload`, um Quellcode auszuführen, wenn die gesamte HTML-Datei geladen ist, alles JavaScript, ...

**Comment by nicolasraube** [comment]
Wieso? Das Laden der HTML Datei würde aufgehalten werden (wir haben auch noch mehrere Scripts, die noch mehr aufhalten) und es wird der selbe Effekt erzielt.
