### ISSUE TITLE
Github-organisation: Logo benutzen

### ISSUE THREAD

**Issue by niccokunzmann** [gruener-campus-malchow/vertretungsplan#71]
Für die Github Organisation auf https://github.com/gruener-campus-malchow
könnten wir das Logo von GCM verwenden.

**Comment by ijontychie** [comment]
Ich bin dafür, dass ihr das Logo als Basis für ein eigenes Logo verwendet. Da der Plan aber ohne Genehmigung seitens Schulleitung nicht offiziell vom GCM ist, können wir nicht einfach das Logo verwenden.

**Comment by nicolasraube** [comment]
![gcmgithublogo](https://cloud.githubusercontent.com/assets/19194376/24333245/d4a0d4a2-1254-11e7-820e-42848884cb3d.png)
@niccokunzmann @ijontychie @Ritze279 Mein Vorschlag für das GCM GitHub Logo.

**Comment by niccokunzmann** [comment]
I mag es :) Die Klammern finde ich gut. Ich denke, du kannst es als Logo setzen.
