### ISSUE TITLE
CSS-class hidden

### ISSUE THREAD

**Issue by niccokunzmann** [gruener-campus-malchow/vertretungsplan#75]
An verschiedenen Stellen werden style-Attribute durch JavaScript gesetzt.
Wir können eine CSS-Klasse benutzen, um das verstecken zu implementieren und diese Klasse kann zum Verschwinden der Elemente hinzugefügt werden und zum Anzeigen entfernt werden.

Beispiele:
```
    document.getElementById('kein-plan').style.display='block';
 -> document.getElementById('kein-plan').classList.remove("hidden")
```
[Quelle](https://github.com/gruener-campus-malchow/vertretungsplan/commit/220711626aed8fafcd0aa9f5ec105978ba350091#diff-ebf70fb415d261b3c5033bf57dba6869R32)

```
    document.getElementById('wrong-pswd').style.display='none';
 -> document.getElementById('kein-plan').classList.add("hidden")
```
[Quelle](https://github.com/gruener-campus-malchow/vertretungsplan/commit/220711626aed8fafcd0aa9f5ec105978ba350091#diff-ebf70fb415d261b3c5033bf57dba6869R36)

Hintergrund zum Lesen:
- https://de.wikipedia.org/wiki/Kopplung_(Softwareentwicklung)#Kopplung_von_Modulen im Zusammenhang mit https://de.wikipedia.org/wiki/Modularit%C3%A4t

**Comment by niccokunzmann** [comment]
:)

**Comment by nicolasraube** [comment]
e.classList kannte ich noch gar nicht, das ist echt praktisch.
