### ISSUE TITLE
Mehrere Tage laden

### ISSUE THREAD

**Issue by nicolasraube** [gruener-campus-malchow/vertretungsplan#84]
Im Moment scheint die API nur den Plan für den aktuellen Tag zurückzuliefern. Wenn schon der Plan für den nächsten Tag online ist, sollten wir den auch anzeigen können.

**Comment by niccokunzmann** [comment]
Braucht das eine Veränderung der API?
In dem Fall, könntest du einen Vorschlag in den Dokuordner einbringen, in ein neues Dokument.
