### ISSUE TITLE
#header-info.onresize => not recalculating plan offset

### ISSUE THREAD

**Issue by nicolasraube** [gruener-campus-malchow/vertretungsplan#88]
offset needs to be recalculated on resize

**Comment by niccokunzmann** [comment]
This can be done with @media in CSS.

**Comment by nicolasraube** [comment]
I mean the top offset. We need to do that in JS because #header-info 's height can change if more information needs to be displayed.
We only need a window.resize listener to call setPlanPaddingTop().

**Comment by niccokunzmann** [comment]
> You don't need JS for MediaQueries to work or to detect the screen size/view port. Also, you do not need to refresh your browser for the result of a MediaQuery to take place.

http://stackoverflow.com/questions/5187390/css-media-queries-as-browser-resizes#5189503

**Comment by niccokunzmann** [comment]
So, it is about resizing if the content changes?

**Comment by nicolasraube** [comment]
I want to measure the height of #header-info, not the screen size.

**Comment by nicolasraube** [comment]
Because if you resize the window width the plan gets covered by it, so we need to change the top padding of #kasten-container.
